included:
  - Sources
  - Tests
excluded:
  - .build
  - Sources/Example
  - Tests/SeedeeKitTests/Resources/Fixtures
disabled_rules:
  - function_parameter_count
  - force_try
  - todo
line_length: 150
file_length: 600
nesting:
  type_level: 2
function_body_length:
  warning: 80
cyclomatic_complexity:
  warning: 15
trailing_comma:
  mandatory_comma: true
type_body_length:
  warning: 400
