version: 2.1

jobs:
  integration-test-ios:
    macos: # https://circleci.com/docs/using-macos
      xcode: 14.0
    steps:
      - checkout
      - run:
          name: Exec integration test
          command: make install test.integration.ios

workflows:
  version: 2
  integration-test-ios:
    jobs:
      - integration-test-ios