# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'SeedeeExample' do
  target 'SeedeeExampleTests' do
    inherit! :search_paths
  end

  target 'SeedeeExampleUITests' do
    inherit! :search_paths
  end
end
