name: Seedee

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  UnitTest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set PULL_REQUEST variable
        run: |
          echo "PULL_REQUEST=$(if [[ ${{ github.event_name }} == 'pull_request' ]]; then echo '1'; else echo '0'; fi)" >> $GITHUB_ENV
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
      - name: SwiftLint
        run: swiftlint --strict
      - name: Build Package
        run: swift build -v
      - name: Set temporary to use in Unit Test
        id: set-temp-dir
        run: |
          echo "TEMP_DIR=$RUNNER_TEMP" >> $GITHUB_ENV
      - name: Create ExportOptions.plist file that supports Unit Test
        run: |
          echo "Creating ExportOptions.plist"
          echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" > $TEMP_DIR/ExportOptions.plist
      - name: Setup Git
        if: env.PULL_REQUEST == '1'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin ${{ github.base_ref }}
      - name: Check for changes in Test files
        if: env.PULL_REQUEST == '1'
        run: |
          DIFF=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})
          CHANGED_TEST_FILES=$(echo "$DIFF" | grep -E '^Tests/.*Test\.swift$' || true)
          echo "CHANGED_TEST_FILES=$CHANGED_TEST_FILES" >> $GITHUB_ENV
      - name: Run Changed Tests
        if: env.PULL_REQUEST == '1' && env.CHANGED_TEST_FILES != ''
        run: |
          for file in $CHANGED_TEST_FILES; do
            test_case_module=$(basename $file .swift)
            echo $test_case_module
            swift test -v -l -s $test_case_module
          done
      - name: Run all tests on main branch
        if: env.PULL_REQUEST == '0'
        run: swift test -v
        env:
          SHOULD_SETUP_COCOAPODS: 1
          SETUP_PROVISIONING_PROFILE: 1
          SKIP_UNIT_TEST: 0
          PROVISIONING_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
