name: Seedee

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  UnitTest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
      - name: SwiftLint
        run: swiftlint --strict
      - name: Build Package
        run: swift build -v
      - name: Create temporary directory
        id: create-temp-dir
        run: |
          temp_dir=$(mktemp -d)
          echo "TEMP_DIR=$temp_dir" >> $GITHUB_ENV
      - name: Create ExportOptions.plist file
        run: |
          echo "Creating ExportOptions.plist"
          echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" > $TEMP_DIR/ExportOptions.plist
      - name: Create Provisoning Profile
        run: |
          echo "Creating Provisioning Profile"
          echo "${{ secrets.PROVISIONING_PROFILE }}" > $TEMP_DIR/seedee_provisoning_profile.obileprovisioning
      - name: Run Unit Tests
        run: swift test -v
        env:
          SHOULD_SETUP_COCOAPODS: 1
