name: Seedee

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  UnitTest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
      - name: SwiftLint
        run: swiftlint --strict
      - name: Build Package
        run: swift build -v
      - name: Set temporary to use in Unit Test
        id: set-temp-dir
        run: |
          echo "TEMP_DIR=$RUNNER_TEMP" >> $GITHUB_ENV
      - name: Create ExportOptions.plist file that supports Unit Test
        run: |
          echo "Creating ExportOptions.plist"
          echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" > $TEMP_DIR/ExportOptions.plist
      - name: Run Unit Tests
        run: swift test -v
        env:
          SHOULD_SETUP_COCOAPODS: 1
          SETUP_PROVISIONING_PROFILE: 1
          SKIP_UNIT_TEST: 0
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
