name: Swift Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  SwiftLint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
      - name: SwiftLint
        run: swiftlint --strict
