name: test
on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:
  test:
    name: Swift-macOS
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode14.0.app
      - name: Integration Test
        run: sh scripts/integration_test_ios.sh
