name: test
on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macOS-latest
          - name: swift-macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Xcode
        run: sudo xcode-selecet --switch /Applications/Xcode14.0.app
      - name: Integration Test
        run: sh scripts/integration_test_ios.sh
