name: test
on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:
  test:
    name: Swift-macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0.0'
      - name: Integration Test
        run: sh scripts/integration_test_ios.sh
